# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogNpm@1
  inputs:
    command: 'install'
    artifactoryConnection: 'Artifactory-Token-Based-Authentication'
    sourceRepo: 'mohsin-npm'
    arguments: 'npm install hello --verbose'

# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'

# - task: JfrogCliV2@1
#   displayName: 'Installing npm package using JFrog CLI command'
#   inputs:
#     jfrogPlatformConnection: 'Artifactory-Platform-Admin-Authentication'
#     command: 'jf npm install hello --verbose'
